# Generated by Django 4.0.3 on 2022-03-07 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
    ]
