# Generated by Django 4.0.3 on 2022-03-07 03:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0005_remove_image_users_like_image_users_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='users_like',
            field=models.ManyToManyField(related_name='images_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
